name: dart_graph_example
description: A simple example of dart airport optimal route search using graph
version: 1.0.0
repository: https://github.com/Lo4D/Dart-Graph-Example

environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
